### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gg1010** [Sqrl34/sqrl-nightclubs#3]
Can you make more or is there only 1

**Comment by Sqrl34** [comment]
As of now there is only 1 club buying location and you can only own 1 club. There are plans to implement this in the future

**Comment by gg1010** [comment]
So you are planing to do so there is multiple locations

**Comment by SynoFPS** [comment]
> So you are planing to do so there is multiple locations

as he just said, yes he is

**Comment by crunchFiveM** [comment]
Amazing work.
Yea adding the option for more locations would really raise the bar.
Awesome and thank you for sharing.

**Comment by Sqrl34** [comment]
@crunchFiveM thanks!
