### ISSUE TITLE
profit

### ISSUE THREAD

**Issue by Tayday937** [Sqrl34/sqrl-nightclubs#7]
were do you collect the club earnings?

**Comment by Sqrl34** [comment]
They should be added directly to the users account 
https://github.com/Sqrl34/sqrl-nightclubs/blob/aa5b9770dc458e9f1d696ebf79d0e3414289c58d/server/main.lua#L189

**Comment by Sqrl34** [comment]
did this solve the question @Tayday937

**Comment by Tayday937** [comment]
yes i will reinstall and try to see if cash/money goes into account later today....thank you for help and reply

**Comment by Sqrl34** [comment]
is this issue able to be resolved?

**Comment by Tayday937** [comment]
> is this issue able to be resolved?

Yes thank u
